version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  dependiences:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  static-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm run lint
workflows:
  tests-build:
    jobs:
      - dependiences
      - static-tests:
          requires:
            - dependiences
