version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  dependiences:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run test
  static-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
      - run: npm run lint
workflows:
  tests-build:
    jobs:
      - dependiences
      - static-tests:
          requires:
            - dependiences
