version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  dependiences:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - save_cache:
          name: Save NPM package cache
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
  static-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
      - node/with-cache:
          steps:
            - run: npm run lint
workflows:
  tests-build:
    jobs:
      - dependiences
      - static-tests:
          requires:
            - dependiences
