version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  dependiences:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
  static-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run lint
  components-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run test
  deploy:
    executor:
      name: node/default
    environment:
      CI: false
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run build
      - run: sudo npm install netlify-cli -g
      - run: npm run build
      - run: netlify deploy --prod --dir build --auth acdccc8efc3c17ec84a54bee2944ae9c2027d438fabf93a2cc787857a29623fe --site bf2810cb-230b-49f4-9721-1c8971fae473
workflows:
  tests-build:
    jobs:
      - dependiences
      - static-tests:
          requires:
            - dependiences
      - components-tests:
          requires:
            - dependiences
      - hold:
          type: approval
          requires:
            - static-tests
            - components-tests
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master

