version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  static-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm run lint
workflows:
  tests-build:
    jobs:
      - static-tests
